apiVersion: v1
kind: Service
metadata:
  name: sample-python-app-service
  labels:
    app: sample-python-app
spec:
  type: LoadBalancer
  selector:
    app: sample-python-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
